<a href="https://colab.research.google.com/github/Chandini-M555/Data_Science_Task/blob/main/DC_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/flats_uncleaned.csv",encoding="ISO-8859-1")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   property_name   4525 non-null   object
 1   areaWithType    4525 non-null   object
 2   square_feet     4525 non-null   object
 3   transaction     4421 non-null   object
 4   status          4524 non-null   object
 5   floor           4480 non-null   object
 6   furnishing      4185 non-null   object
 7   facing          3936 non-null   object
 8   description     3154 non-null   object
 9   price_per_sqft  4157 non-null   object
 10  price           4525 non-null   object
dtypes: object(11)
memory usage: 389.0+ KB

In [ ]:
#Removing dupliactes
df.shape
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(4416, 11)

In [ ]:
#removing null values
df.isnull().sum()

property_name        0
areaWithType         0
square_feet          0
transaction        103
status               1
floor               45
furnishing         331
facing             563
description       1331
price_per_sqft     358
price                0
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

property_name     0
areaWithType      0
square_feet       0
transaction       0
status            0
floor             0
furnishing        0
facing            0
description       0
price_per_sqft    0
price             0
dtype: int64

In [ ]:
#checking evry column
df["property_name"].unique()

array(['2 BHK Apartment for Sale in Dindoli Surat',
       '2 BHK Apartment for Sale in Althan Surat',
       '2 BHK Apartment for Sale in Pal Gam Surat', ...,
       '4 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat',
       '5 BHK Apartment for Sale in Sangini Arise, Bharthana Surat',
       '5 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat'],
      dtype=object)

In [ ]:
#checking for extra spaces
df["property_name"] = df["property_name"].str.strip()
df["property_name"].unique()

array(['2 BHK Apartment for Sale in Dindoli Surat',
       '2 BHK Apartment for Sale in Althan Surat',
       '2 BHK Apartment for Sale in Pal Gam Surat', ...,
       '4 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat',
       '5 BHK Apartment for Sale in Sangini Arise, Bharthana Surat',
       '5 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat'],
      dtype=object)

In [ ]:
df["areaWithType"].unique() #no issues

array(['Carpet Area', 'Super Area', 'Plot Area'], dtype=object)

In [ ]:
df["square_feet"].unique()
#here already the column name is square feet...so only numerical value is enough

array(['644 sqft', '1278 sqft', '1173 sqft', ..., '2970 sqft',
       '2545 sqft', '2620 sqft'], dtype=object)

In [ ]:
#removing sqft from every record
df["square_feet"]=df["square_feet"].str.strip(" sqft")
df["square_feet"].unique()

array(['644', '1278', '1173', ..., '2970', '2545', '2620'], dtype=object)

In [ ]:
df.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","â¹2,891 per sqft",â¹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"â¹3,551 per sqft",â¹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"â¹3,800 per sqft",â¹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"â¹3,966 per sqft",â¹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","â¹3,600 per sqft",â¹45 Lac

In [ ]:
df["transaction"].unique()
#there are mixing of records here

array(['New Property', 'Resale', 'Orchid Fantasia', 'Unfurnished',
       'Orchid Gardenia', 'Congo', 'Furnished', '3', 'Semi-Furnished',
       '2', '4', '1', 'Soham Elegance', '5', 'Co-operative Society',
       'Raghuvir Silverstone', 'Casa Rivera'], dtype=object)

In [ ]:
df["transaction"].value_counts() #the actual records should be either New_property or Resale...remaining are errors

transaction
New Property            1229
Resale                  1001
Unfurnished              270
Semi-Furnished            36
Furnished                 35
3                         15
2                         12
4                          5
Orchid Gardenia            3
5                          3
Congo                      3
1                          3
Soham Elegance             3
Orchid Fantasia            2
Raghuvir Silverstone       2
Casa Rivera                2
Co-operative Society       1
Name: count, dtype: int64

In [ ]:
#Changing the data present inside columns
#d={"New_Prop Property":"New","Unfurnished":"Resale","Orchid Fantasia":"New",....} #so many records to change
#df["transaction"]=df["transaction"].map(d)

array(['New_Prop Property', 'Resale', 'Orchid Fantasia', 'Unfurnished',
       'Orchid Gardenia', 'Congo', 'Furnished', '3', 'Semi-Furnished',
       '2', '4', '1', 'Soham Elegance', '5', 'Co-operative Society',
       'Raghuvir Silverstone', 'Casa Rivera'], dtype=object)

In [ ]:
df["status"].unique()
df["status"].value_counts()
#mixing of different attributes

status
Ready to Move       1585
Poss. by Dec '24     139
Poss. by Dec '25      93
Poss. by Apr '25      65
Poss. by Jul '24      53
                    ...
240 X 180              1
Poss. by Mar '28       1
1200 X 3               1
144 X 105              1
Poss. by Nov '28       1
Name: count, Length: 110, dtype: int64

In [ ]:
#removing the unwanted column- description
df=df.drop(["description"],axis=1)
df.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"â¹2,891 per sqft",â¹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,"â¹3,551 per sqft",â¹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,"â¹3,800 per sqft",â¹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700,New Property,Ready to Move,6 out of 14,Unfurnished,East,"â¹3,966 per sqft",â¹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250,Orchid Fantasia,New Property,Unfurnished,2,2,"â¹3,600 per sqft",â¹45 Lac

In [ ]:
df["floor"].unique()
df["floor"].value_counts()

floor
New Property    213
5 out of 13     191
Resale          167
7 out of 13     118
6 out of 13     106
               ...
9 out of 18       1
16 out of 18      1
2 out of 17       1
9 out of 17       1
1 out of 18       1
Name: count, Length: 186, dtype: int64

In [ ]:
#removing new property and resales from floor column
df["floor"]=df["floor"].replace("New Property","0")
df["floor"]=df["floor"].replace("Resale","0")
df["floor"].value_counts()

floor
0               380
5 out of 13     191
7 out of 13     118
6 out of 13     106
5 out of 12      99
               ...
9 out of 18       1
16 out of 18      1
2 out of 17       1
9 out of 17       1
1 out of 18       1
Name: count, Length: 185, dtype: int64

In [ ]:
df["price_per_sqft"].unique()

array(['â\x82¹2,891 per sqft ', 'â\x82¹3,551 per sqft ',
       'â\x82¹3,800 per sqft ', ..., 'â\x82¹8,512 per sqft ',
       'â\x82¹8,200 per sqft ', 'â\x82¹5,756 per sqft '], dtype=object)

In [ ]:
#removing per sqft
df["price_per_sqft"]=df["price_per_sqft"].str.strip(" per sqft")
df["price_per_sqft"].unique()

array(['â\x82¹2,891', 'â\x82¹3,551', 'â\x82¹3,800', ..., 'â\x82¹8,512',
       'â\x82¹8,200', 'â\x82¹5,756'], dtype=object)

In [ ]:
#removing â\x82¹ from the record and comma
df["price_per_sqft"]=df["price_per_sqft"].str.strip("â\x82¹")
df["price_per_sqft"]=df["price_per_sqft"].str.replace(",","")
df["price_per_sqft"].unique()

array(['2891', '3551', '3800', ..., '8512', '8200', '5756'], dtype=object)

In [ ]:
#conversion of data type to int
df["price_per_sqft"]=df["price_per_sqft"].astype(float)
df["price_per_sqft"]=df["price_per_sqft"].astype(int)
df["price_per_sqft"].unique()

array([2891, 3551, 3800, ..., 8512, 8200, 5756])

In [ ]:
#remove price column
df=df.drop(["price"],axis=1)
df.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,price_per_sqft
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644,New_Prop Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,2891
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278,New_Prop Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,3551
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,3800
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700,New_Prop Property,Ready to Move,6 out of 14,Unfurnished,East,3966
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250,Orchid Fantasia,New Property,Unfurnished,2,2,3600